In [6]:
import numpy as np

In [3]:
#1
array=np.array([0,1,2,3,4,5,6,7,8,9])

print(array[0:9])

[0 1 2 3 4 5 6 7 8]


In [4]:
#2
boo = np.ones((3,3), dtype=bool)
print(boo)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [53]:
#3
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2 == 1]
print("odd numbers =", a[a%2 == 1])

odd numbers = [1 3 5 7 9]


In [57]:
#4
a = np.array([1,2,3,4,5,6,7,8,9,10])
minus_one = a[a%2 == 1] = -1 
print("Odd numbers replaced with:",minus_one) 

Odd numbers replaced with: -1


In [59]:
#5
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
newArray=array.reshape(2,8)
print(newArray)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [27]:
#6
array_a = np.array([1, 2, 3, 4])
array_b = np.array([5, 6, 7, 8])
ar_v = np.vstack((array_a, array_b))
np.dot = (array_a, array_b)
np.sum = (array_a, array_b)

print(np.dot)
print(np.sum)

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))
(array([1, 2, 3, 4]), array([5, 6, 7, 8]))


In [28]:
#Extension1

n = 4
arr = np.array([n-3, n-3, n-3, n-2, n-2, n-2, n-1, n-1, n-1,n-3, n-2, n-1,n-3, n-2, n-1,n-3, n-2, n-1])
print ("#>array", (arr))

#>array [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [7]:
#Extension2

a = np.array(list(range(1,6)))
b = np.array(list(range(4,10)))
c = np.union1d(a, b)
print(c)

[1 2 3 4 5 6 7 8 9]


In [23]:
#Extension3
a = np.array(list(range(1,6)))
b = np.array(list(range(4,10)))
c = np.union1d(a, b)
items3to7 = c[3:7]

print("sum=", np.sum(items3to7))


sum= 22


In [43]:
ones=np.ones(20)

print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
random=np.random.rand(3,4)

print (random)

[[0.0759162  0.06093471 0.45610947 0.3258713 ]
 [0.50584022 0.28316093 0.79142329 0.40102646]
 [0.00190728 0.80291719 0.84537049 0.74019515]]


In [10]:
eye=np.eye(8)

print (eye)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [14]:
even=np.arange(0, 50,10)

print (even)

[ 0 10 20 30 40]


In [15]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
newArray=array.reshape(4,4)
print(newArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
array=np.arange(0,5)
print(array)
print("Subtract:", array-2)
print("Multiply:", array*2)
print("Divide:", array/2)
print("Power:", array**2)

[0 1 2 3 4]
Subtract: [-2 -1  0  1  2]
Multiply: [0 2 4 6 8]
Divide: [0.  0.5 1.  1.5 2. ]
Power: [ 0  1  4  9 16]


In [21]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
c=np.dot(a,b)
print(c)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [22]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
c=np.dot(a,b)
sum=np.sum(c)
print(sum)

1944
